# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: NPM Publish Github Packages

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          
      - name: Test and build
        run: |
          npm ci
          npm test
          npm run build

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://npm.pkg.github.com/

      - name: Get release branch from tag
        id: get_branch
        run: |
          # Get the commit hash for this tag
          TAG="${GITHUB_REF#refs/tags/}"
          COMMIT_HASH=$(git rev-list -n 1 "$TAG")
          # Find remote branches that contain this commit
          BRANCH=$(git branch -r --contains "$COMMIT_HASH" | grep -v '\->' | grep -E 'origin/main|origin/master' | head -n 1 | sed 's|origin/||' | xargs)
          echo "branch=$BRANCH" >> $GITHUB_OUTPUT

      - name: Checkout the release branch
        if: steps.get_branch.outputs.branch != ''
        run: |
          git fetch origin ${{ steps.get_branch.outputs.branch }}
          git checkout ${{ steps.get_branch.outputs.branch }}

      - name: Update package.json version
        run: |
          TAG_VERSION="${GITHUB_REF#refs/tags/}"
          VERSION="${TAG_VERSION#v}"
          npm version --no-git-tag-version "$VERSION"

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add package.json package-lock.json || true
          git commit -m "chore: update package.json version to $VERSION [skip ci]" || exit 0
          git push origin HEAD
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Publish to GitHub npm packages
        run: |
          npm ci
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
